version: '0.1'
networks: 
  - "host"
services: 
  plex:
    image: "plexinc/pms-docker"    
    ports:
      - "32400:32400/tcp"
    environment:
      - "TZ=Europe/Paris"
      - PLEX_CLAIM=claim-rfE3Rw5BEBsHEukPFFy1
    volumes:
      - config:/config 
      - transcode:/transcode
      - data:/data
  radarr:
    image: "linuxserver/radarr"
    ports:
      -  "7878:7878"
    environment: 
      - "TZ=Europe/Paris"
    volumes: 
      - configradarr:/config
      - transcode:/downloads
      - movie/movies
  sonarr:
    image: "linuxserver/sonarr"
    ports:
      -  "8989:8989"
    environment: 
      - "TZ=Europe/Paris"
    volumes: 
      - configsonarr:/config
      - transcode:/downloads
      - TV/tv
  lidarr:
    image: "linuxserver/lidarr"
    ports:
      -  "8686:8686"
    environment: 
      - "TZ=Europe/Paris"
    volumes: 
      - configs:/config
      - transcode:/downloads
      - comics/comics
  deluge:
    image: "linuxserver/deluge"
    ports:
      -  "8080:8112"
    environment: 
      - "TZ=Europe/Paris"
    volumes: 
      - configs:/config
      - downloads:/downloads    